# Generated by Django 3.0.6 on 2020-05-26 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussboard', '0003_auto_20200522_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='Comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
